### ISSUE TITLE
🚨 blocker: the library can't be used at the moment 🚨

### ISSUE THREAD

**Issue by noomorph** [marcbouchenoire/dimmmensions#128]
### Steps to reproduce

```bash
npm init -y
npm install dimmmensions
node -p 'require("dimmmensions").getDimensions(1170, 2532)'
```

### Actual result

```plain text
TypeError: Cannot read properties of undefined (reading 'screen')
    at /Users/yaroslavs/Projects/wix-private/oops/node_modules/dimmmensions/dist/index.js:1:10485
    at Array.filter (<anonymous>)
    at exports.getDimensions (/Users/yaroslavs/Projects/wix-private/oops/node_modules/dimmmensions/dist/index.js:1:10445)
    at [eval]:1:25
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:313:38)
    at node:internal/process/execution:79:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:78:60)
    at node:internal/main/eval_string:28:3
```

### Expected result

Can be achieved via workaround:

```
node -p 'require("dimmmensions").dimensions.splice(14, 1), require("dimmmensions").getDimensions(1170, 2532)'
```

where the element at index 14 is almost empty `{ name: 'iPhone 8' }` object.

<summary>

<details>

```js
[
  {
    device: 'iPhone',
    landscape: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    name: 'iPhone 12',
    portrait: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    radius: 47.33,
    scale: 3
  },
  {
    device: 'iPhone',
    landscape: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    name: 'iPhone 13',
    portrait: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    radius: 47.33,
    scale: 3
  },
  {
    device: 'iPhone',
    landscape: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    name: 'iPhone 12 Pro',
    portrait: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    radius: 47.33,
    scale: 3
  },
  {
    device: 'iPhone',
    landscape: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    name: 'iPhone 14',
    portrait: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    radius: 47.33,
    scale: 3
  },
  {
    device: 'iPhone',
    landscape: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    name: 'iPhone 13 Pro',
    portrait: {
      screen: [Object],
      sizeClass: [Object],
      layoutMargins: [Object],
      readableContent: [Object],
      safeArea: [Object]
    },
    radius: 47.33,
    scale: 3
  }
]
```

</details>
</summary>

🎩 Thanks for the cooperation!

**Comment by marcbouchenoire** [comment]
Hi! Sorry for the late reply, I'll push a fix shortly and add more tests to avoid this in the future.

**Comment by marcbouchenoire** [comment]
[`2.3.1`](https://github.com/marcbouchenoire/dimmmensions/releases/tag/dimmmensions%402.3.1) is out and fixes the issue.
